### Create
POST http://localhost:3000/writers
Content-Type: application/json

{
  "name": "Tezuka Yoshioka",
  "email": "yooshioka@gmail.com",
  "dateOfBirth": "2003-08-18"
}

### Get all
GET http://localhost:3000/writers

### Get by ID
GET http://localhost:3000/writers/yYUyZSPhuWQhdWvreORHU

### Update ID
PATCH http://localhost:3000/writers/yYUyZSPhuWQhdWvreORHU
Content-Type: application/json

{
  "email": "yoshiokaseijuro@gmail.com"
}

### Delete by ID
DELETE http://localhost:3000/writers/XyfLphfcfCnythbJ6vWjz