### Create
POST http://localhost:3000/writters
Content-Type: application/json

{
  "name": "Tezuka Yoshioka",
  "email": "yooshioka@gmail.com",
  "dateOfBirth": "2003-08-18"
}

### Get all
GET http://localhost:3000/writters

### Get by ID
GET http://localhost:3000/writters/yYUyZSPhuWQhdWvreORHU

### Update ID
PATCH http://localhost:3000/writters/yYUyZSPhuWQhdWvreORHU
Content-Type: application/json

{
  "email": "yoshiokaseijuro@gmail.com"
}

### Delete by ID
DELETE http://localhost:3000/writters/XyfLphfcfCnythbJ6vWjz